import { z } from "zod";
import { STALL_AFTER_DAYS } from "../insights/stall.js";

/**
 * Nudges, and the settings that govern them (FR-N1, FR-N3, FR-N4, FR-N5).
 *
 * **"Quiet by default" is a delivery decision, not an off switch.** FR-N4 says notifications must be
 * configurable and quiet by default, because "a nagging app gets muted, then deleted". Read as
 * off-until-enabled, the feature would ship dead: nobody turns on notifications they have never
 * seen. Read as *passive*, it is the same argument §14.1 makes about the changelog — "not a modal,
 * not a takeover". So these are generated by default and delivered as a marker and a line inside the
 * app. There is no push channel, no sound, and nothing that can interrupt a focus session. Each kind
 * can be switched off.
 *
 * **No streaks, forgiving or otherwise** (FR-N5). The one kind that could have been one — "you have
 * not logged in for N days" — is deliberately absent. Stall detection asks about a *mission*, and
 * its suggested action is to park it, which is the opposite of a guilt trip.
 */

export const NOTIFICATION_KINDS = ["weekly_review", "stall"] as const;
export type NotificationKind = (typeof NOTIFICATION_KINDS)[number];
export const NotificationKindSchema = z.enum(NOTIFICATION_KINDS);

/**
 * Both configs are **strict**, which is doing real work here rather than being fussy.
 *
 * Zod strips unknown keys by default, so a weekly-review config posted against `stall` would parse
 * happily, drop the fields the user set, and store the defaults — a setting that silently did not
 * take. This column is jsonb, and strictness is the only thing standing between it and a junk
 * drawer.
 */

/** 0 = Sunday, matching `Profile.weekStartsOn` and `Date.getUTCDay`. */
export const WeeklyReviewConfigSchema = z.strictObject({
  weekday: z.coerce.number().int().min(0).max(6).default(0),
  /**
   * Local hour, 0–23. Sunday evening by default: the review is about the week that just ended, and
   * asking on Monday morning competes with the week that just started.
   */
  hour: z.coerce.number().int().min(0).max(23).default(18),
});
export type WeeklyReviewConfig = z.infer<typeof WeeklyReviewConfigSchema>;

export const StallConfigSchema = z.strictObject({
  /** FR-N3's own example is 12 days. */
  afterDays: z.coerce.number().int().min(3).max(90).default(STALL_AFTER_DAYS),
});
export type StallConfig = z.infer<typeof StallConfigSchema>;

/**
 * One preference row, discriminated by kind so each carries only its own knobs.
 *
 * A discriminated union rather than a bag of optional fields: `notification_prefs.config` is jsonb,
 * and the thing that stops jsonb becoming a junk drawer is a schema that refuses to store
 * `afterDays` against a weekly review.
 */
export const NotificationPrefSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("weekly_review"),
    enabled: z.boolean().default(true),
    config: WeeklyReviewConfigSchema.default({ weekday: 0, hour: 18 }),
  }),
  z.object({
    kind: z.literal("stall"),
    enabled: z.boolean().default(true),
    config: StallConfigSchema.default({ afterDays: STALL_AFTER_DAYS }),
  }),
]);
export type NotificationPref = z.infer<typeof NotificationPrefSchema>;

export const UpdateNotificationPrefsSchema = z.object({
  prefs: z.array(NotificationPrefSchema).max(NOTIFICATION_KINDS.length),
});
export type UpdateNotificationPrefsInput = z.infer<typeof UpdateNotificationPrefsSchema>;

/** Every kind on, at its defaults. What a profile with no rows behaves as. */
export function defaultNotificationPrefs(): readonly NotificationPref[] {
  return NOTIFICATION_KINDS.map((kind) => NotificationPrefSchema.parse({ kind }));
}
