import { z } from "zod";
import { STALL_AFTER_DAYS } from "../insights/stall.js";

/**
 * Nudges, and the settings that govern them (FR-N1, FR-N3, FR-N4, FR-N5).
 *
 * **"Quiet by default" is a delivery decision, not an off switch.** FR-N4 says notifications must be
 * configurable and quiet by default, because "a nagging app gets muted, then deleted". Read as
 * off-until-enabled, the feature would ship dead: nobody turns on notifications they have never
 * seen. Read as *passive*, it is the same argument §14.1 makes about the changelog — "not a modal,
 * not a takeover". So these are generated by default and delivered as a marker and a line inside the
 * app. There is no push channel, no sound, and nothing that can interrupt a focus session. Each kind
 * can be switched off.
 *
 * **No streaks, forgiving or otherwise** (FR-N5). The one kind that could have been one — "you have
 * not logged in for N days" — is deliberately absent. Stall detection asks about a *mission*, and
 * its suggested action is to park it, which is the opposite of a guilt trip.
 */

export const NOTIFICATION_KINDS = ["weekly_review", "stall"] as const;
export type NotificationKind = (typeof NOTIFICATION_KINDS)[number];
export const NotificationKindSchema = z.enum(NOTIFICATION_KINDS);

/**
 * Both configs are **strict**, which is doing real work here rather than being fussy.
 *
 * Zod strips unknown keys by default, so a weekly-review config posted against `stall` would parse
 * happily, drop the fields the user set, and store the defaults — a setting that silently did not
 * take. This column is jsonb, and strictness is the only thing standing between it and a junk
 * drawer.
 */

/** 0 = Sunday, matching `Profile.weekStartsOn` and `Date.getUTCDay`. */
export const WeeklyReviewConfigSchema = z.strictObject({
  weekday: z.coerce.number().int().min(0).max(6).default(0),
  /**
   * Local hour, 0–23. Sunday evening by default: the review is about the week that just ended, and
   * asking on Monday morning competes with the week that just started.
   */
  hour: z.coerce.number().int().min(0).max(23).default(18),
});
export type WeeklyReviewConfig = z.infer<typeof WeeklyReviewConfigSchema>;

export const StallConfigSchema = z.strictObject({
  /** FR-N3's own example is 12 days. */
  afterDays: z.coerce.number().int().min(3).max(90).default(STALL_AFTER_DAYS),
});
export type StallConfig = z.infer<typeof StallConfigSchema>;

/**
 * One preference row, discriminated by kind so each carries only its own knobs.
 *
 * A discriminated union rather than a bag of optional fields: `notification_prefs.config` is jsonb,
 * and the thing that stops jsonb becoming a junk drawer is a schema that refuses to store
 * `afterDays` against a weekly review.
 */
export const NotificationPrefSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("weekly_review"),
    enabled: z.boolean().default(true),
    config: WeeklyReviewConfigSchema.default({ weekday: 0, hour: 18 }),
  }),
  z.object({
    kind: z.literal("stall"),
    enabled: z.boolean().default(true),
    config: StallConfigSchema.default({ afterDays: STALL_AFTER_DAYS }),
  }),
]);
export type NotificationPref = z.infer<typeof NotificationPrefSchema>;

export const UpdateNotificationPrefsSchema = z.object({
  prefs: z.array(NotificationPrefSchema).max(NOTIFICATION_KINDS.length),
});
export type UpdateNotificationPrefsInput = z.infer<typeof UpdateNotificationPrefsSchema>;

/** Every kind on, at its defaults. What a profile with no rows behaves as. */
export function defaultNotificationPrefs(): readonly NotificationPref[] {
  return NOTIFICATION_KINDS.map((kind) => NotificationPrefSchema.parse({ kind }));
}

/**
 * The payload each `kind` carries — the ICU arguments its message is rendered with.
 *
 * **This exists because the two sides drifted and neither's tests could notice.** The worker wrote
 * `{ topic, untouchedDays }`; the SPA read `missionTopic`, found nothing, and rendered "a mission has
 * gone quiet" — losing the one thing FR-N3 exists to say. Both suites passed, because each asserted
 * against its own spelling. A shared schema is the only thing that makes that impossible rather than
 * unlikely: the producer builds through it and the consumer parses through it, so a rename that
 * misses one side fails to compile.
 *
 * The field names are the **ICU argument names** in the `settings` locale bundle, not the domain's — the
 * payload's whole job is to be spread into a message, and a translator reading `{missionTopic}`
 * should find that name here.
 */
export const StallPayloadSchema = z.strictObject({
  missionTopic: z.string().min(1),
  days: z.number().int().min(0),
});
export type StallPayload = z.infer<typeof StallPayloadSchema>;

/** The weekly review nudge is about the week, not a thing in it. */
export const WeeklyReviewPayloadSchema = z.strictObject({
  weekStart: z.string(),
});
export type WeeklyReviewPayload = z.infer<typeof WeeklyReviewPayloadSchema>;

export const NOTIFICATION_PAYLOAD_SCHEMAS = {
  stall: StallPayloadSchema,
  weekly_review: WeeklyReviewPayloadSchema,
} as const satisfies Record<NotificationKind, unknown>;

/**
 * Reading stored preferences back, shared by the API and the nightly worker.
 *
 * It lived in `apps/api` and the worker had its own version, which diverged in the way that matters:
 * the worker discarded a row whose `config` no longer parsed and replaced it with the default, so a
 * user who had *muted* stall nudges kept receiving them after a release renamed a config key — while
 * Settings, reading the API's version, still showed them as off. Two implementations of one rule,
 * disagreeing about the only field FR-N4 says is load-bearing.
 *
 * One row of `notification_prefs` as Postgres hands it over.
 *
 * `config` is `unknown` because the column is jsonb: whatever shape the build that wrote it
 * believed in is what comes back, and this build has to decide what to make of it.
 */
export interface StoredNotificationPref {
  readonly kind: string;
  readonly enabled: boolean;
  readonly config: unknown;
}

/**
 * Validate on the way **out**, not only on the way in.
 *
 * A row written by an older version of the app is the case that would otherwise reach the SPA
 * malformed — the request schema only ever saw the requests this build accepted, and jsonb keeps
 * whatever it was given. `NotificationPrefSchema` is strict, so a renamed or dropped config key
 * fails here rather than becoming a settings screen that renders undefined.
 *
 * Null means the row cannot be understood at all and the caller should fall back to the default.
 */
export function readStoredPref(row: StoredNotificationPref): NotificationPref | null {
  const whole = NotificationPrefSchema.safeParse(row);
  if (whole.success) return whole.data;

  // A config we can no longer parse must not silently un-mute something the user switched off.
  // FR-N4's entire argument is that "a nagging app gets muted, then deleted", so the switch is the
  // setting that matters most — and `enabled` is a boolean column with no shape to drift. Keep it,
  // and let only the unreadable config fall back to its defaults.
  const switchOnly = NotificationPrefSchema.safeParse({ kind: row.kind, enabled: row.enabled });
  return switchOnly.success ? switchOnly.data : null;
}

/**
 * The stored rows over the defaults, so a profile with no rows behaves as every kind enabled.
 *
 * Merged at read time and **never seeded**: a seeded row would freeze today's defaults into an
 * account forever, so changing what "quiet by default" means would reach new users and nobody else.
 * The absence of a row is the setting.
 *
 * Order follows `NOTIFICATION_KINDS` — via `defaultNotificationPrefs`, which is built from it —
 * rather than whatever order Postgres returned the rows in. Sorting `kind` in SQL would be
 * alphabetical, which is the trap this codebase has fallen into twice.
 */
export function mergeNotificationPrefs(
  stored: readonly NotificationPref[],
): readonly NotificationPref[] {
  const byKind = new Map(stored.map((pref) => [pref.kind, pref]));
  return defaultNotificationPrefs().map((fallback) => byKind.get(fallback.kind) ?? fallback);
}
